In [74]:
import numpy as np
import pandas as pd

Problem 1

In [3]:
a=np.random.randint(1,51,(5,4))
print(a)

[[48 16 20 29]
 [37 36 31 38]
 [12 36 26 21]
 [13 31 25  3]
 [30  4 12  4]]


In [4]:
anti_diagonal=[a[i][3-i] for i in range(0,4)]

print(anti_diagonal)

[29, 31, 36, 13]


In [6]:
np.mean(a)

23.6

In [9]:
new_arr=a[np.where(a>np.mean(a))]

print(new_arr)

[48 29 37 36 31 38 36 26 31 25 30]


In [51]:
def numpy_boundary_traversal(f ):
    l=[]
    l.append(f[0])
    l.append(f[1:-1,-1])
    l.append(f[-1,-1::-1])
    l.append(f[-2:0:-1,0])
    ans=[]
    for i in l:
        ans.extend(i)
    
    return ans

print(a)
print(numpy_boundary_traversal(a))

    

[[48 16 20 29]
 [37 36 31 38]
 [12 36 26 21]
 [13 31 25  3]
 [30  4 12  4]]
[48, 16, 20, 29, 38, 21, 3, 4, 12, 4, 30, 13, 12, 37]


Problem 2

In [69]:
b=np.random.uniform(0,11,20)
print(b)

b=b.round(2)

print(b)

[ 7.93246006  5.68489721  0.61966869  8.97302082  4.87833858  8.48242026
  0.86834192  0.68831813  2.05266085  0.39727029  0.15666272  4.08889679
  1.60744175 10.19936165 10.64245049  4.97764985  6.36861033  8.93290371
  4.07120168  5.9133227 ]
[ 7.93  5.68  0.62  8.97  4.88  8.48  0.87  0.69  2.05  0.4   0.16  4.09
  1.61 10.2  10.64  4.98  6.37  8.93  4.07  5.91]


In [70]:
median=np.median(b)
min=np.min(b)
max=np.max(b)


print('min=',min," ,max=", max, " ,median=", median)

min= 0.16  ,max= 10.64  ,median= 4.93


In [71]:
c=np.where(b<5,b**2,b)

print(c)

[ 7.93    5.68    0.3844  8.97   23.8144  8.48    0.7569  0.4761  4.2025
  0.16    0.0256 16.7281  2.5921 10.2    10.64   24.8004  6.37    8.93
 16.5649  5.91  ]


In [72]:
def numpy_alternate_array(array):

    sorted=np.sort(array)
    result=[]
    i, j = 0, len(sorted) - 1
    while i <= j:
        result.append(sorted[i])
        i += 1
        if i <= j:
            result.append(sorted[j])
            j -= 1

    return np.array(result)


print(b)
print(numpy_alternate_array(b))

[ 7.93  5.68  0.62  8.97  4.88  8.48  0.87  0.69  2.05  0.4   0.16  4.09
  1.61 10.2  10.64  4.98  6.37  8.93  4.07  5.91]
[ 0.16 10.64  0.4  10.2   0.62  8.97  0.69  8.93  0.87  8.48  1.61  7.93
  2.05  6.37  4.07  5.91  4.09  5.68  4.88  4.98]


Problem 3

In [78]:
names = ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
subjects = ['Math', 'Science', 'English', 'History', 'Geography']

num_records = 10
np.random.seed(0)  

data = {
    'Name': np.random.choice(names, size=num_records),
    'Subject': np.random.choice(subjects, size=num_records),
    'Score': np.random.randint(50, 101, size=num_records)  
}

In [83]:
df=pd.DataFrame(data)


# A (90–100), B (80–89), C (70–79), D (60–69), F(below 60).
def assign(score):
    if score>=90:
        return 'A'
    elif score>=80:
        return 'B'
    elif score>=70:
        return 'C'
    elif score>=60:
        return 'D'
    else:
        return 'F'


df["Grade"]=[assign(i) for i in df["Score"]]


print(df)


      Name    Subject  Score Grade
0      Eva       Math     66     D
1    Alice  Geography     55     F
2    David    English     65     D
3    David    Science     97     A
4    David       Math     50     F
5      Bob    Science     68     D
6    David    Science     85     B
7  Charlie       Math     74     C
8      Eva    Science     99     A
9    Alice  Geography     79     C


In [87]:
print(df.sort_values("Score",ascending=False))

      Name    Subject  Score Grade
8      Eva    Science     99     A
3    David    Science     97     A
6    David    Science     85     B
9    Alice  Geography     79     C
7  Charlie       Math     74     C
5      Bob    Science     68     D
0      Eva       Math     66     D
2    David    English     65     D
1    Alice  Geography     55     F
4    David       Math     50     F


In [86]:
avg_scores = df.groupby('Subject')['Score'].mean()

print( avg_scores)

Subject
English      65.000000
Geography    67.000000
Math         63.333333
Science      87.250000
Name: Score, dtype: float64


In [88]:
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]


In [89]:
passed_df = pandas_filter_pass(df)
print(passed_df)

    Name  Subject  Score Grade
3  David  Science     97     A
6  David  Science     85     B
8    Eva  Science     99     A
